"""Utilities for a notebook implementation of LookingGlass.

The implementation follows the paper's SD3/rectified-flow formulation:

1. predict a clean latent from the current flow-model velocity;
2. decode clean latents into image space;
3. synchronize views with Laplacian Pyramid Warping (LPW);
4. re-encode synchronized images and add a latent residual correction;
5. take a FlowMatch Euler transition, including paper-style time-travel jumps.

UV maps are normalized to [0, 1] and map target-view pixels back into the
canonical image. Undefined pixels can be represented with NaN.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Callable, Iterable, Optional, Sequence

import numpy as np
import torch
import torch.nn.functional as F


@dataclass
class ViewSpec:
    """A text prompt and its target-to-canonical UV warp."""

    name: str
    prompt: str
    uv: torch.Tensor


def make_identity_uv(height: int, width: int, *, device=None, dtype=torch.float32) -> torch.Tensor:
    y, x = torch.meshgrid(
        torch.linspace(0, 1, height, device=device, dtype=dtype),
        torch.linspace(0, 1, width, device=device, dtype=dtype),
        indexing="ij",
    )
    return torch.stack([x, y], dim=-1)


def make_flip_uv(height: int, width: int, *, axis: str = "vertical", device=None, dtype=torch.float32) -> torch.Tensor:
    uv = make_identity_uv(height, width, device=device, dtype=dtype)
    if axis == "vertical":
        uv[..., 1] = 1 - uv[..., 1]
    elif axis == "horizontal":
        uv[..., 0] = 1 - uv[..., 0]
    else:
        raise ValueError("axis must be 'vertical' or 'horizontal'")
    return uv


def make_rotate_uv(
    height: int,
    width: int,
    *,
    angle_degrees: float,
    center: tuple[float, float] = (0.5, 0.5),
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """Target-to-canonical UV for rotating the canonical image by angle_degrees."""

    uv = make_identity_uv(height, width, device=device, dtype=dtype)
    cx, cy = center
    theta = math.radians(-angle_degrees)
    cos_t, sin_t = math.cos(theta), math.sin(theta)
    x = uv[..., 0] - cx
    y = uv[..., 1] - cy
    src_x = cos_t * x - sin_t * y + cx
    src_y = sin_t * x + cos_t * y + cy
    out = torch.stack([src_x, src_y], dim=-1)
    return out


def make_inner_rotate_uv(
    height: int,
    width: int,
    *,
    angle_degrees: float = 135.0,
    radius: float = 0.42,
    center: tuple[float, float] = (0.5, 0.5),
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """Rotate only a central disk; useful for reproducing the 135 degree paper task."""

    base = make_identity_uv(height, width, device=device, dtype=dtype)
    rot = make_rotate_uv(height, width, angle_degrees=angle_degrees, center=center, device=device, dtype=dtype)
    cx, cy = center
    dist = torch.sqrt((base[..., 0] - cx) ** 2 + (base[..., 1] - cy) ** 2)
    return torch.where((dist <= radius)[..., None], rot, base)


def make_conic_mirror_uv(
    height: int,
    width: int,
    *,
    center: tuple[float, float] = (0.5, 0.5),
    target_radius: float = 0.49,
    ring_inner: float = 0.18,
    ring_outer: float = 0.49,
    radial_flip: bool = True,
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """Analytic cone-like UV map.

    A real conic mirror UV is best generated by ray tracing. This procedural map
    captures the useful layout: the hidden view is remapped into an annular band
    around the mirror footprint.
    """

    target = make_identity_uv(height, width, device=device, dtype=dtype)
    cx, cy = center
    dx = target[..., 0] - cx
    dy = target[..., 1] - cy
    r = torch.sqrt(dx * dx + dy * dy)
    theta = torch.atan2(dy, dx)
    normalized_r = r / max(target_radius, 1e-6)
    annulus_t = 1 - normalized_r if radial_flip else normalized_r
    src_r = ring_inner + annulus_t * (ring_outer - ring_inner)
    src_x = cx + src_r * torch.cos(theta)
    src_y = cy + src_r * torch.sin(theta)
    uv = torch.stack([src_x, src_y], dim=-1)
    valid = normalized_r <= 1.0
    uv = torch.where(valid[..., None], uv, torch.full_like(uv, torch.nan))
    return uv


def make_cylindrical_mirror_uv(
    height: int,
    width: int,
    *,
    center: tuple[float, float] = (0.5, 0.5),
    ring_inner: float = 0.18,
    ring_outer: float = 0.49,
    angle_start: float = -math.pi,
    angle_end: float = math.pi,
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """Analytic cylinder-like UV map that unwraps a rectangular view into a ring."""

    target = make_identity_uv(height, width, device=device, dtype=dtype)
    cx, cy = center
    theta = angle_start + target[..., 0] * (angle_end - angle_start)
    radius = ring_inner + target[..., 1] * (ring_outer - ring_inner)
    src_x = cx + radius * torch.cos(theta)
    src_y = cy + radius * torch.sin(theta)
    uv = torch.stack([src_x, src_y], dim=-1)
    valid = (uv[..., 0] >= 0) & (uv[..., 0] <= 1) & (uv[..., 1] >= 0) & (uv[..., 1] <= 1)
    return torch.where(valid[..., None], uv, torch.full_like(uv, torch.nan))


def make_oblique_cylindrical_mirror_uv(
    height: int,
    width: int,
    *,
    center: tuple[float, float] = (0.5, 0.17),
    radius: float = 0.125,
    mirror_height: float = 0.30,
    mirror_z_min: float = 0.02,
    view_angle_degrees: float = 60.0,
    view_azimuth_degrees: float = 90.0,
    visible_arc_degrees: float = 130.0,
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """Orthographic ray-traced UV map for a vertical cylindrical mirror.

    The UV convention is image-like: u=0 left, v=0 top. The physical plane is
    centered at the origin with side length 1, and +Y points toward the top of
    the image. `view_angle_degrees` is the angle between the cylinder axis and
    the viewing ray. `view_azimuth_degrees=90` means the camera is below the
    picture looking toward +Y.
    """

    target = make_identity_uv(height, width, device=device, dtype=dtype)
    target_u = target[..., 0]
    target_v = target[..., 1]

    cx = center[0] - 0.5
    cy = 0.5 - center[1]

    theta = math.radians(view_angle_degrees)
    azimuth = math.radians(view_azimuth_degrees)
    hdir = torch.tensor([math.cos(azimuth), math.sin(azimuth)], device=device, dtype=dtype)
    hdir = hdir / torch.linalg.vector_norm(hdir).clamp_min(1e-6)

    n0 = -hdir
    right = torch.stack([hdir[1], -hdir[0]])
    arc = math.radians(visible_arc_degrees)
    surface_angle = (target_u - 0.5) * arc
    normal_x = torch.cos(surface_angle) * n0[0] + torch.sin(surface_angle) * right[0]
    normal_y = torch.cos(surface_angle) * n0[1] + torch.sin(surface_angle) * right[1]

    p_x = cx + radius * normal_x
    p_y = cy + radius * normal_y
    p_z = mirror_z_min + (1.0 - target_v) * max(mirror_height - mirror_z_min, 1e-6)

    d_x = hdir[0] * math.sin(theta)
    d_y = hdir[1] * math.sin(theta)
    d_z = -math.cos(theta)
    dn = d_x * normal_x + d_y * normal_y
    r_x = d_x - 2.0 * dn * normal_x
    r_y = d_y - 2.0 * dn * normal_y

    t = -p_z / d_z
    hit_x = p_x + t * r_x
    hit_y = p_y + t * r_y

    src_u = hit_x + 0.5
    src_v = 0.5 - hit_y
    uv = torch.stack([src_u, src_v], dim=-1)

    front_facing = dn < 0
    in_bounds = (src_u >= 0) & (src_u <= 1) & (src_v >= 0) & (src_v <= 1)
    valid = front_facing & in_bounds
    return torch.where(valid[..., None], uv, torch.full_like(uv, torch.nan))


def make_faceted_lens_uv(
    height: int,
    width: int,
    *,
    center: tuple[float, float] = (0.5, 0.5),
    radius: float = 0.48,
    facets: int = 9,
    strength: float = 0.12,
    device=None,
    dtype=torch.float32,
) -> torch.Tensor:
    """A small procedural UV map inspired by Niceron's faceted lens.

    For physically accurate lens effects, replace this with a ray-traced UV map.
    """

    uv = make_identity_uv(height, width, device=device, dtype=dtype)
    cx, cy = center
    dx = uv[..., 0] - cx
    dy = uv[..., 1] - cy
    r = torch.sqrt(dx * dx + dy * dy)
    theta = torch.atan2(dy, dx)
    facet_theta = torch.round(theta * facets / (2 * math.pi)) * (2 * math.pi / facets)
    src_theta = theta + strength * torch.sin(facet_theta * 3.0) * (1 - r / max(radius, 1e-6))
    src_r = r * (1 + strength * torch.cos(facet_theta * 2.0))
    src_x = cx + src_r * torch.cos(src_theta)
    src_y = cy + src_r * torch.sin(src_theta)
    out = torch.stack([src_x, src_y], dim=-1)
    valid = r <= radius
    return torch.where(valid[..., None], out, uv)


def _as_batched_uv(uv: torch.Tensor) -> torch.Tensor:
    if uv.dim() == 3:
        uv = uv.unsqueeze(0)
    if uv.dim() != 4 or uv.shape[-1] != 2:
        raise ValueError("uv must have shape [H, W, 2] or [B, H, W, 2]")
    return uv


def resize_uv(uv: torch.Tensor, height: int, width: int) -> torch.Tensor:
    uv = _as_batched_uv(uv)
    if uv.shape[1] == height and uv.shape[2] == width:
        return uv

    valid = torch.isfinite(uv).all(dim=-1, keepdim=True)
    uv_clean = torch.where(valid, uv, torch.zeros_like(uv))
    uv_chw = uv_clean.permute(0, 3, 1, 2)
    uv_resized = F.interpolate(uv_chw, size=(height, width), mode="bilinear", align_corners=True).permute(0, 2, 3, 1)

    valid_chw = valid.float().permute(0, 3, 1, 2)
    valid_resized = F.interpolate(valid_chw, size=(height, width), mode="nearest").permute(0, 2, 3, 1) > 0.5
    return torch.where(valid_resized, uv_resized, torch.full_like(uv_resized, torch.nan))


def valid_uv_mask(uv: torch.Tensor) -> torch.Tensor:
    uv = _as_batched_uv(uv)
    finite = torch.isfinite(uv).all(dim=-1, keepdim=True)
    in_bounds = (uv[..., :1] >= 0) & (uv[..., :1] <= 1) & (uv[..., 1:] >= 0) & (uv[..., 1:] <= 1)
    return finite & in_bounds


def is_identity_uv(uv: torch.Tensor, *, atol: float = 1e-5) -> bool:
    uv = _as_batched_uv(uv)
    if uv.shape[0] != 1 or not valid_uv_mask(uv).all().item():
        return False
    ref = make_identity_uv(uv.shape[1], uv.shape[2], device=uv.device, dtype=uv.dtype).unsqueeze(0)
    return torch.max(torch.abs(uv - ref)).item() <= atol


def _blur5(x: torch.Tensor) -> torch.Tensor:
    kernel_1d = torch.tensor([1, 4, 6, 4, 1], device=x.device, dtype=x.dtype) / 16.0
    channels = x.shape[1]
    ky = kernel_1d.view(1, 1, 5, 1).repeat(channels, 1, 1, 1)
    kx = kernel_1d.view(1, 1, 1, 5).repeat(channels, 1, 1, 1)
    x = F.pad(x, (0, 0, 2, 2), mode="reflect")
    x = F.conv2d(x, ky, groups=channels)
    x = F.pad(x, (2, 2, 0, 0), mode="reflect")
    x = F.conv2d(x, kx, groups=channels)
    return x


def pyr_down(x: torch.Tensor) -> torch.Tensor:
    h, w = x.shape[-2:]
    if h <= 1 or w <= 1:
        return x
    blurred = _blur5(x)
    return blurred[..., ::2, ::2]


def pyr_up(x: torch.Tensor, size: tuple[int, int]) -> torch.Tensor:
    out_h, out_w = size
    up = torch.zeros(
        (*x.shape[:-2], out_h, out_w),
        device=x.device,
        dtype=x.dtype,
    )
    slots = up[..., ::2, ::2]
    copy_h = min(slots.shape[-2], x.shape[-2])
    copy_w = min(slots.shape[-1], x.shape[-1])
    slots[..., :copy_h, :copy_w] = x[..., :copy_h, :copy_w]
    return 4.0 * _blur5(up)


def clamp_pyramid_levels(height: int, width: int, requested_levels: int) -> int:
    max_levels = 1
    h, w = height, width
    while min(h, w) >= 8:
        max_levels += 1
        h //= 2
        w //= 2
    return max(1, min(requested_levels, max_levels))


def gaussian_pyramid(image: torch.Tensor, levels: int) -> list[torch.Tensor]:
    levels = clamp_pyramid_levels(image.shape[-2], image.shape[-1], levels)
    out = [image]
    for _ in range(1, levels):
        out.append(pyr_down(out[-1]))
    return out


def laplacian_pyramid(image: torch.Tensor, levels: int) -> list[torch.Tensor]:
    gp = gaussian_pyramid(image, levels)
    out: list[torch.Tensor] = []
    for idx in range(len(gp) - 1):
        out.append(gp[idx] - pyr_up(gp[idx + 1], gp[idx].shape[-2:]))
    out.append(gp[-1])
    return out


def laplacian_to_gaussian(lp: Sequence[torch.Tensor]) -> list[torch.Tensor]:
    gp: list[Optional[torch.Tensor]] = [None for _ in lp]
    gp[-1] = lp[-1]
    for idx in range(len(lp) - 2, -1, -1):
        gp[idx] = lp[idx] + pyr_up(gp[idx + 1], lp[idx].shape[-2:])
    return [x for x in gp if x is not None]


def reconstruct_laplacian(lp: Sequence[torch.Tensor]) -> torch.Tensor:
    return laplacian_to_gaussian(lp)[0]


def pyramid_stack(pyramid: Sequence[torch.Tensor]) -> torch.Tensor:
    """Upsample a pyramid to full resolution and stack it for 5D sampling.

    This mirrors the supplementary pseudo-code's ``pyrStack(lp, dim=-1)``:
    each level is expanded back to level-0 resolution with the pyramid's
    upsampling operator, then stacked as a depth dimension. The returned tensor
    has shape ``[B, C, L, H, W]`` so PyTorch's 5D ``grid_sample`` can sample
    spatial position and LOD in one nearest-neighbor lookup.
    """

    if not pyramid:
        raise ValueError("pyramid must contain at least one level")

    base_h, base_w = pyramid[0].shape[-2:]
    batch = max(level.shape[0] for level in pyramid)
    channels = pyramid[0].shape[1]
    shapes = [level.shape[-2:] for level in pyramid]

    stacked: list[torch.Tensor] = []
    for level_index, level_image in enumerate(pyramid):
        if level_image.shape[1] != channels:
            raise ValueError("all pyramid levels must have the same channel count")

        upsampled = level_image.float()
        if upsampled.shape[0] == 1 and batch > 1:
            upsampled = upsampled.expand(batch, -1, -1, -1)
        elif upsampled.shape[0] != batch:
            raise ValueError("all pyramid levels must have batch size 1 or the same batch size")

        for target_level in range(level_index - 1, -1, -1):
            upsampled = pyr_up(upsampled, shapes[target_level])

        if upsampled.shape[-2:] != (base_h, base_w):
            raise RuntimeError("pyramid upsampling did not recover the base resolution")
        stacked.append(upsampled)

    return torch.stack(stacked, dim=2)


def compute_lod_level(uv: torch.Tensor, *, max_lod: int) -> torch.Tensor:
    """Compute texture-mapping LOD from target-to-canonical UV derivatives."""

    uv = _as_batched_uv(uv).float()
    b, h, w, _ = uv.shape
    finite = valid_uv_mask(uv)
    mapping = torch.where(finite, uv, torch.zeros_like(uv))
    scale = torch.tensor([max(w, 1), max(h, 1)], device=uv.device, dtype=uv.dtype)
    mapping = (mapping * scale).permute(0, 3, 1, 2)

    dx = mapping[..., :, 1:] - mapping[..., :, :-1]
    dx = F.pad(dx, (0, 1, 0, 0), mode="replicate")
    dy = mapping[..., 1:, :] - mapping[..., :-1, :]
    dy = F.pad(dy, (0, 0, 0, 1), mode="replicate")

    rho_x = torch.linalg.vector_norm(dx, dim=1)
    rho_y = torch.linalg.vector_norm(dy, dim=1)
    rho = torch.maximum(rho_x, rho_y).clamp_min(1e-6)
    lod = torch.log2(rho).clamp(0, float(max_lod))
    lod = torch.where(finite.squeeze(-1), lod, torch.zeros_like(lod))
    return lod.unsqueeze(1)


def uv_to_grid(uv: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    uv = _as_batched_uv(uv)
    valid = valid_uv_mask(uv)
    grid = 2.0 * torch.where(valid, uv, torch.zeros_like(uv)) - 1.0
    grid = torch.where(valid, grid, torch.full_like(grid, 2.0))
    return grid, valid.permute(0, 3, 1, 2).float()


def forward_lpw_from_gaussian(
    gp: Sequence[torch.Tensor],
    uv: torch.Tensor,
    *,
    lod: Optional[torch.Tensor] = None,
    fill_value: float = 0.0,
    sample_mode: str = "nearest",
    return_mask: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
    """Forward Laplacian Pyramid Warping using page-13-style 5D sampling."""

    layers = pyramid_stack(gp).to(device=gp[0].device, dtype=torch.float32)
    _, _, level_count, height, width = layers.shape
    uv = resize_uv(uv.to(layers.device), height, width).float()
    grid_xy, valid = uv_to_grid(uv)

    b = max(layers.shape[0], uv.shape[0])
    if layers.shape[0] == 1 and b > 1:
        layers = layers.expand(b, -1, -1, -1, -1)
    elif layers.shape[0] != b:
        raise ValueError("pyramid batch size must be 1 or match the UV batch size")
    if grid_xy.shape[0] == 1 and b > 1:
        grid_xy = grid_xy.expand(b, -1, -1, -1)
        valid = valid.expand(b, -1, -1, -1)
    elif grid_xy.shape[0] != b:
        raise ValueError("UV batch size must be 1 or match the pyramid batch size")

    max_lod = level_count - 1
    if lod is None:
        lod = compute_lod_level(uv, max_lod=max_lod)
    if lod.shape[0] == 1 and b > 1:
        lod = lod.expand(b, -1, -1, -1)
    elif lod.shape[0] != b:
        raise ValueError("LOD batch size must be 1 or match the pyramid batch size")

    lod = lod.to(device=layers.device, dtype=torch.float32).clamp(0.0, float(max_lod))
    if max_lod == 0:
        lod_grid = torch.zeros_like(lod)
    else:
        lod_grid = 2.0 * lod / float(max_lod) - 1.0
    lod_grid = lod_grid.permute(0, 2, 3, 1)

    # PyTorch 5D grid_sample expects coordinates in (x, y, z) order,
    # corresponding here to (u, v, LOD). The paper writes this grid
    # conceptually as (LOD, u, v) before its pyrStack helper.
    grid = torch.cat([grid_xy, lod_grid], dim=-1).unsqueeze(1)
    out = F.grid_sample(
        layers,
        grid,
        mode=sample_mode,
        padding_mode="zeros",
        align_corners=True,
    ).squeeze(2)

    out = torch.where(valid.bool(), out, torch.full_like(out, fill_value))
    if return_mask:
        return out, valid
    return out


def forward_lpw(
    image: torch.Tensor,
    uv: torch.Tensor,
    *,
    levels: int = 6,
    fill_value: float = 0.0,
    sample_mode: str = "nearest",
    return_mask: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
    gp = gaussian_pyramid(image.float(), levels)
    return forward_lpw_from_gaussian(gp, uv, fill_value=fill_value, sample_mode=sample_mode, return_mask=return_mask)


def sample_tensor_with_uv(
    tensor: torch.Tensor,
    uv: torch.Tensor,
    *,
    sample_mode: str = "nearest",
    fill_value: float = 0.0,
    return_mask: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
    """Sample a tensor with a target-to-source UV map."""

    original_dtype = tensor.dtype
    uv = resize_uv(uv.to(tensor.device), tensor.shape[-2], tensor.shape[-1]).float()
    grid, valid = uv_to_grid(uv)
    batch = max(tensor.shape[0], grid.shape[0])
    if tensor.shape[0] == 1 and batch > 1:
        tensor = tensor.expand(batch, -1, -1, -1)
    if grid.shape[0] == 1 and batch > 1:
        grid = grid.expand(batch, -1, -1, -1)
        valid = valid.expand(batch, -1, -1, -1)

    out = F.grid_sample(tensor.float(), grid, mode=sample_mode, padding_mode="zeros", align_corners=True)
    out = torch.where(valid.bool(), out, torch.full_like(out, fill_value))
    out = out.to(dtype=original_dtype)
    if return_mask:
        return out, valid
    return out


def synchronize_tensors_with_uv(
    tensors: torch.Tensor,
    view_uvs: Sequence[torch.Tensor],
    inverse_uvs: Sequence[torch.Tensor],
    *,
    sample_mode: str = "nearest",
) -> torch.Tensor:
    """Visual-Anagrams-style canonical averaging for arbitrary tensors."""

    if tensors.shape[0] != len(view_uvs) or tensors.shape[0] != len(inverse_uvs):
        raise ValueError("tensor batch, view_uvs, and inverse_uvs must have the same length")

    canonical_values = []
    canonical_masks = []
    for idx in range(tensors.shape[0]):
        value, mask = sample_tensor_with_uv(
            tensors[idx : idx + 1],
            inverse_uvs[idx].to(tensors.device),
            sample_mode=sample_mode,
            return_mask=True,
        )
        canonical_values.append(value.float())
        canonical_masks.append(mask.float())

    value_stack = torch.cat(canonical_values, dim=0)
    mask_stack = torch.cat(canonical_masks, dim=0)
    canonical = (value_stack * mask_stack).sum(dim=0, keepdim=True) / mask_stack.sum(dim=0, keepdim=True).clamp_min(1.0)

    synced = []
    for idx in range(tensors.shape[0]):
        synced.append(
            sample_tensor_with_uv(
                canonical,
                view_uvs[idx].to(tensors.device),
                sample_mode=sample_mode,
                fill_value=0.0,
            )
        )
    return torch.cat(synced, dim=0).to(dtype=tensors.dtype)


def impute_with_nearest(values: torch.Tensor, missing_mask: torch.Tensor) -> torch.Tensor:
    """Fill missing pixels with the nearest defined pixel.

    This uses scipy's distance transform on CPU; the tensors are returned on the
    original device and dtype.
    """

    try:
        from scipy.ndimage import distance_transform_edt
    except Exception as exc:  # pragma: no cover - only used when scipy is absent
        raise ImportError("scipy is required for nearest-neighbor imputation") from exc

    device, dtype = values.device, values.dtype
    x = values.detach().float().cpu()
    mask = missing_mask.detach().cpu().bool()
    if mask.shape[1] != 1:
        mask = mask.any(dim=1, keepdim=True)

    out = x.clone()
    for bi in range(x.shape[0]):
        missing = mask[bi, 0].numpy()
        valid = ~missing
        if valid.all():
            continue
        if not valid.any():
            out[bi].zero_()
            continue
        indices = distance_transform_edt(missing, return_distances=False, return_indices=True)
        nearest = x[bi, :, indices[0], indices[1]]
        out[bi] = nearest
    return out.to(device=device, dtype=dtype)


def inverse_lpw(
    image: torch.Tensor,
    uv: torch.Tensor,
    *,
    levels: int = 6,
    eps: float = 1e-6,
    sample_mode: str = "nearest",
) -> list[torch.Tensor]:
    """Inverse Laplacian Pyramid Warping using a differentiable dummy pass."""

    image = image.float()
    uv = resize_uv(uv.to(image.device), image.shape[-2], image.shape[-1]).float()
    levels = clamp_pyramid_levels(image.shape[-2], image.shape[-1], levels)

    if is_identity_uv(uv):
        return laplacian_pyramid(image, levels)

    b, c, h, w = image.shape
    shapes = [(h, w)]
    for _ in range(1, levels):
        h = max(1, (h + 1) // 2)
        w = max(1, (w + 1) // 2)
        shapes.append((h, w))

    with torch.enable_grad():
        opt_lp = [
            torch.zeros((b, c + 1, hh, ww), device=image.device, dtype=torch.float32, requires_grad=True)
            for hh, ww in shapes
        ]
        opt_gp = laplacian_to_gaussian(opt_lp)
        target = torch.cat([image, torch.ones((b, 1, image.shape[-2], image.shape[-1]), device=image.device)], dim=1)
        warped, valid = forward_lpw_from_gaussian(
            opt_gp,
            uv,
            fill_value=0.0,
            sample_mode=sample_mode,
            return_mask=True,
        )
        loss = 0.5 * (((warped - target) * valid) ** 2).sum()
        loss.backward()

        transported = []
        for level in opt_lp:
            grad = -level.grad.detach()
            denom = grad[:, c : c + 1].clamp_min(eps)
            color = grad[:, :c] / denom
            missing = grad[:, c : c + 1] <= eps
            color = torch.where(missing, torch.full_like(color, torch.nan), color)
            transported.append(color)

    result: list[torch.Tensor] = []
    for idx, color in enumerate(transported):
        missing = ~torch.isfinite(color).all(dim=1, keepdim=True)
        imputed = impute_with_nearest(torch.nan_to_num(color, nan=0.0), missing)
        if idx < len(transported) - 1:
            lap = imputed - pyr_up(pyr_down(imputed), imputed.shape[-2:])
        else:
            lap = imputed
        lap = torch.where(missing, torch.full_like(lap, torch.nan), lap)
        result.append(lap)
    return result


def blend_laplacian_pyramids(pyramids: Sequence[Sequence[torch.Tensor]], *, alpha: float = 0.35) -> list[torch.Tensor]:
    """Blend partial Laplacian pyramids with optional value-weighted averaging."""

    if not pyramids:
        raise ValueError("at least one pyramid is required")

    blended: list[torch.Tensor] = []
    for level in range(len(pyramids[0])):
        stack = torch.stack([p[level].float() for p in pyramids], dim=0)
        valid = torch.isfinite(stack)
        safe = torch.where(valid, stack, torch.zeros_like(stack))

        count = valid.float().sum(dim=0).clamp_min(1.0)
        avg = safe.sum(dim=0) / count

        abs_safe = safe.abs()
        denom = (abs_safe * valid.float()).sum(dim=0).clamp_min(1e-6)
        vavg = (abs_safe * safe).sum(dim=0) / denom

        out = avg + float(alpha) * (vavg - avg)
        has_value = valid.any(dim=0)
        out = torch.where(has_value, out, torch.full_like(out, torch.nan))
        blended.append(out)
    return blended


def calculate_shift(
    image_seq_len: int,
    base_seq_len: int = 256,
    max_seq_len: int = 4096,
    base_shift: float = 0.5,
    max_shift: float = 1.16,
) -> float:
    m = (max_shift - base_shift) / (max_seq_len - base_seq_len)
    b = base_shift - m * base_seq_len
    return image_seq_len * m + b


def module_device(module) -> torch.device:
    return next(module.parameters()).device


def module_dtype(module) -> torch.dtype:
    return next(module.parameters()).dtype


def pipe_execution_device(pipe) -> torch.device:
    return getattr(pipe, "_execution_device", module_device(pipe.vae))


def vae_decode_tensor(pipe, latents: torch.Tensor) -> torch.Tensor:
    scaling = pipe.vae.config.scaling_factor
    shift = getattr(pipe.vae.config, "shift_factor", 0.0)
    vae_latents = (latents / scaling) + shift
    image = pipe.vae.decode(vae_latents.to(device=pipe_execution_device(pipe), dtype=module_dtype(pipe.vae)), return_dict=False)[0]
    return image.float().clamp(-1, 1)


def vae_encode_tensor(pipe, image: torch.Tensor, *, generator=None) -> torch.Tensor:
    scaling = pipe.vae.config.scaling_factor
    shift = getattr(pipe.vae.config, "shift_factor", 0.0)
    image = image.to(device=pipe_execution_device(pipe), dtype=module_dtype(pipe.vae)).clamp(-1, 1)
    latent_dist = pipe.vae.encode(image).latent_dist
    if generator is not None:
        latents = latent_dist.sample(generator=generator)
    elif hasattr(latent_dist, "mode"):
        latents = latent_dist.mode()
    else:
        latents = latent_dist.mean
    return ((latents - shift) * scaling).float()


def synchronize_clean_latents(
    pipe,
    clean_latents: torch.Tensor,
    uvs: Sequence[torch.Tensor],
    *,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    lpw_sample_mode: str = "nearest",
    active_indices: Optional[Sequence[int]] = None,
) -> torch.Tensor:
    """Apply LookingGlass view synchronization to predicted clean latents."""

    device = clean_latents.device
    dtype = clean_latents.dtype
    view_count = clean_latents.shape[0]
    if len(uvs) != view_count:
        raise ValueError("number of UV maps must match the latent batch size")
    active = list(range(view_count)) if active_indices is None else list(active_indices)

    decoded: list[torch.Tensor] = []
    roundtrip_residuals: list[torch.Tensor] = []
    for idx in range(view_count):
        with torch.no_grad():
            image = vae_decode_tensor(pipe, clean_latents[idx : idx + 1])
            reencoded = vae_encode_tensor(pipe, image).to(device=device)
        decoded.append(image.float())
        roundtrip_residuals.append((clean_latents[idx : idx + 1].float() - reencoded.float()).to(device))

    image_pyrs = [
        inverse_lpw(decoded[idx], uvs[idx].to(device), levels=image_levels, sample_mode=lpw_sample_mode)
        for idx in active
    ]
    canonical_lp = blend_laplacian_pyramids(image_pyrs, alpha=alpha)
    canonical_gp = laplacian_to_gaussian(canonical_lp)

    encoded_views: list[torch.Tensor] = []
    for idx in range(view_count):
        image_uv = resize_uv(uvs[idx].to(device), decoded[idx].shape[-2], decoded[idx].shape[-1])
        synced_image = forward_lpw_from_gaussian(
            canonical_gp,
            image_uv,
            fill_value=0.0,
            sample_mode=lpw_sample_mode,
        )
        with torch.no_grad():
            encoded = vae_encode_tensor(pipe, synced_image).to(device=device)
        encoded_views.append(encoded.float())

    residual_levels = clamp_pyramid_levels(clean_latents.shape[-2], clean_latents.shape[-1], latent_levels)
    residual_pyrs = [
        inverse_lpw(
            roundtrip_residuals[idx],
            uvs[idx].to(device),
            levels=residual_levels,
            sample_mode=lpw_sample_mode,
        )
        for idx in active
    ]
    canonical_residual_lp = blend_laplacian_pyramids(residual_pyrs, alpha=0.0)
    canonical_residual_gp = laplacian_to_gaussian(canonical_residual_lp)

    out: list[torch.Tensor] = []
    for idx in range(view_count):
        latent_uv = resize_uv(uvs[idx].to(device), clean_latents.shape[-2], clean_latents.shape[-1])
        residual = forward_lpw_from_gaussian(
            canonical_residual_gp,
            latent_uv,
            fill_value=0.0,
            sample_mode=lpw_sample_mode,
        )
        out.append(encoded_views[idx] + residual.float())
    return torch.cat(out, dim=0).to(dtype=dtype)


def set_sd3_timesteps(pipe, latents: torch.Tensor, num_inference_steps: int, *, device, sigmas=None, mu=None):
    scheduler_kwargs = {}
    if pipe.scheduler.config.get("use_dynamic_shifting", None) and mu is None:
        _, _, height, width = latents.shape
        image_seq_len = (height // pipe.transformer.config.patch_size) * (width // pipe.transformer.config.patch_size)
        scheduler_kwargs["mu"] = calculate_shift(
            image_seq_len,
            pipe.scheduler.config.get("base_image_seq_len", 256),
            pipe.scheduler.config.get("max_image_seq_len", 4096),
            pipe.scheduler.config.get("base_shift", 0.5),
            pipe.scheduler.config.get("max_shift", 1.16),
        )
    elif mu is not None:
        scheduler_kwargs["mu"] = mu

    if sigmas is not None:
        pipe.scheduler.set_timesteps(sigmas=sigmas, device=device, **scheduler_kwargs)
    else:
        pipe.scheduler.set_timesteps(num_inference_steps, device=device, **scheduler_kwargs)
    return pipe.scheduler.timesteps


def timestep_from_sigma(pipe, sigma: torch.Tensor, *, device) -> torch.Tensor:
    """Convert a FlowMatch sigma value back to the model timestep scale."""

    return sigma.to(device=device, dtype=torch.float32) * pipe.scheduler.config.num_train_timesteps


def flowmatch_euler_step(
    sample: torch.Tensor,
    model_output: torch.Tensor,
    current_sigma: torch.Tensor,
    next_sigma: torch.Tensor,
) -> torch.Tensor:
    """FlowMatch Euler transition for arbitrary forward or backward sigma jumps."""

    dtype = sample.dtype
    while current_sigma.ndim < sample.ndim:
        current_sigma = current_sigma.unsqueeze(-1)
    while next_sigma.ndim < sample.ndim:
        next_sigma = next_sigma.unsqueeze(-1)
    out = sample.float() + (next_sigma.float() - current_sigma.float()) * model_output.float()
    return out.to(dtype=dtype)


def time_travel_transitions(
    total_steps: int,
    *,
    sync_repeat_start: float = 0.20,
    sync_repeat_stop: float = 0.80,
    sync_repeats: int = 1,
) -> list[tuple[int, int, int]]:
    """Build one-step denoise/noise-back transitions for paper-style time travel.

    Each tuple is `(base_step_index, current_sigma_index, next_sigma_index)`.
    For `sync_repeats=N`, timesteps in the selected range become:
    `i -> i+1 -> i -> i+1 ...`, ending at `i+1`.
    """

    first_repeat = int(total_steps * sync_repeat_start)
    last_repeat = int(total_steps * sync_repeat_stop)
    repeat_count = max(1, int(sync_repeats))

    transitions: list[tuple[int, int, int]] = []
    for step_index in range(total_steps):
        repeats = repeat_count if first_repeat <= step_index < last_repeat and step_index < total_steps - 1 else 1
        for repeat_index in range(repeats):
            transitions.append((step_index, step_index, step_index + 1))
            if repeat_index < repeats - 1:
                transitions.append((step_index, step_index + 1, step_index))
    return transitions


def encode_sd3_prompts(
    pipe,
    prompts: Sequence[str],
    *,
    negative_prompts: Optional[Sequence[str]] = None,
    device,
    do_classifier_free_guidance: bool = True,
    max_sequence_length: int = 256,
):
    if negative_prompts is None:
        negative_prompts = ["" for _ in prompts]

    prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds = pipe.encode_prompt(
        prompt=list(prompts),
        prompt_2=list(prompts),
        prompt_3=list(prompts),
        negative_prompt=list(negative_prompts),
        negative_prompt_2=list(negative_prompts),
        negative_prompt_3=list(negative_prompts),
        do_classifier_free_guidance=do_classifier_free_guidance,
        device=device,
        num_images_per_prompt=1,
        max_sequence_length=max_sequence_length,
    )

    if do_classifier_free_guidance:
        prompt_embeds = torch.cat([negative_prompt_embeds, prompt_embeds], dim=0)
        pooled_prompt_embeds = torch.cat([negative_pooled_prompt_embeds, pooled_prompt_embeds], dim=0)
    return prompt_embeds, pooled_prompt_embeds


def predict_velocity_sd3(
    pipe,
    latents: torch.Tensor,
    timestep: torch.Tensor,
    prompt_embeds: torch.Tensor,
    pooled_prompt_embeds: torch.Tensor,
    *,
    guidance_scale: float,
) -> torch.Tensor:
    do_cfg = guidance_scale is not None and guidance_scale > 1.0
    latent_model_input = torch.cat([latents] * 2) if do_cfg else latents
    timestep_batch = timestep.expand(latent_model_input.shape[0])
    noise_pred = pipe.transformer(
        hidden_states=latent_model_input,
        timestep=timestep_batch,
        encoder_hidden_states=prompt_embeds,
        pooled_projections=pooled_prompt_embeds,
        joint_attention_kwargs=getattr(pipe, "joint_attention_kwargs", None),
        return_dict=False,
    )[0]

    if do_cfg:
        noise_uncond, noise_text = noise_pred.chunk(2)
        noise_pred = noise_uncond + guidance_scale * (noise_text - noise_uncond)
    return noise_pred

def sample_lookingglass(
    pipe,
    views: Sequence[ViewSpec],
    *,
    height: int = 1024,
    width: int = 1024,
    num_inference_steps: int = 30,
    guidance_scale: float = 4.5,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    lpw_sample_mode: str = "nearest",
    seed: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    negative_prompts: Optional[Sequence[str]] = None,
    sync_repeat_start: float = 0.20,
    sync_repeat_stop: float = 0.80,
    sync_repeats: int = 1,
    prioritize_view: Optional[int] = 0,
    prioritize_fraction: float = 0.20,
    max_sequence_length: int = 256,
    correlated_initial_noise: bool = False,
    callback: Optional[Callable[[int, torch.Tensor, torch.Tensor], None]] = None,
) -> dict:
    """Generate a LookingGlass illusion with Stable Diffusion 3/3.5 pipelines.

    `sync_repeats` follows the paper's time-travel convention: selected
    one-step denoising segments are expanded into forward/backward sigma
    transitions and then re-denoised, rather than merely repeating LPW sync.
    By default, each view starts from an independent Gaussian latent, matching
    Algorithm 1. Set `correlated_initial_noise=True` to initialize every view
    from one UV-transformed base latent for Visual-Anagrams-style experiments.
    """

    if not views:
        raise ValueError("at least one ViewSpec is required")

    device = pipe._execution_device if hasattr(pipe, "_execution_device") else torch.device("cuda")
    dtype = module_dtype(pipe.transformer)
    if generator is None and seed is not None:
        generator = torch.Generator(device=device).manual_seed(seed)

    prompts = [view.prompt for view in views]
    uvs = [resize_uv(view.uv.to(device), height, width) for view in views]
    do_cfg = guidance_scale is not None and guidance_scale > 1.0

    prompt_embeds, pooled_prompt_embeds = encode_sd3_prompts(
        pipe,
        prompts,
        negative_prompts=negative_prompts,
        device=device,
        do_classifier_free_guidance=do_cfg,
        max_sequence_length=max_sequence_length,
    )

    num_channels_latents = pipe.transformer.config.in_channels
    if correlated_initial_noise:
        base_latents = pipe.prepare_latents(
            1,
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents=None,
        )
        latent_height = base_latents.shape[-2]
        latent_width = base_latents.shape[-1]
        latent_view_uvs = [resize_uv(uv.to(device), latent_height, latent_width) for uv in uvs]
        latents = torch.cat(
            [
                sample_tensor_with_uv(
                    base_latents,
                    latent_view_uvs[idx],
                    sample_mode=lpw_sample_mode,
                    fill_value=0.0,
                )
                for idx in range(len(views))
            ],
            dim=0,
        )
    else:
        latents = pipe.prepare_latents(
            len(views),
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents=None,
        )

    timesteps = set_sd3_timesteps(pipe, latents, num_inference_steps, device=device)
    sigmas = pipe.scheduler.sigmas.to(device=device, dtype=latents.dtype)
    total_steps = len(timesteps)
    transitions = time_travel_transitions(
        total_steps,
        sync_repeat_start=sync_repeat_start,
        sync_repeat_stop=sync_repeat_stop,
        sync_repeats=sync_repeats,
    )
    first_prioritize = int(total_steps * (1.0 - prioritize_fraction))

    for transition_index, (step_index, sigma_index, next_sigma_index) in enumerate(transitions):
        sigma = sigmas[sigma_index].to(device=latents.device, dtype=latents.dtype)
        next_sigma = sigmas[next_sigma_index].to(device=latents.device, dtype=latents.dtype)
        timestep = timestep_from_sigma(pipe, sigma, device=latents.device)

        with torch.no_grad():
            velocity = predict_velocity_sd3(
                pipe,
                latents,
                timestep,
                prompt_embeds,
                pooled_prompt_embeds,
                guidance_scale=guidance_scale,
            )

        clean_latents = latents - sigma * velocity

        active_indices = None
        if prioritize_view is not None and prioritize_fraction > 0 and step_index >= first_prioritize:
            active_indices = [int(prioritize_view)]

        synced_clean = synchronize_clean_latents(
            pipe,
            clean_latents,
            uvs,
            image_levels=image_levels,
            latent_levels=latent_levels,
            alpha=alpha,
            lpw_sample_mode=lpw_sample_mode,
            active_indices=active_indices,
        )

        synced_velocity = (latents - synced_clean) / sigma.clamp_min(1e-6)
        latents_dtype = latents.dtype
        latents = flowmatch_euler_step(latents, synced_velocity, sigma, next_sigma)
        latents = latents.to(latents_dtype).detach()

        if callback is not None:
            callback(transition_index, timestep, latents)

    with torch.no_grad():
        decoded = vae_decode_tensor(pipe, latents)
        images = pipe.image_processor.postprocess(decoded, output_type="pil")

    return {
        "images": images,
        "latents": latents,
        "views": views,
        "prompts": prompts,
    }


def fake_timetravel_sample_lookingglass(
    pipe,
    views: Sequence[ViewSpec],
    *,
    height: int = 1024,
    width: int = 1024,
    num_inference_steps: int = 30,
    guidance_scale: float = 4.5,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    lpw_sample_mode: str = "nearest",
    seed: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    negative_prompts: Optional[Sequence[str]] = None,
    sync_repeat_start: float = 0.20,
    sync_repeat_stop: float = 0.80,
    sync_repeats: int = 1,
    prioritize_view: Optional[int] = 0,
    prioritize_fraction: float = 0.20,
    max_sequence_length: int = 256,
    correlated_initial_noise: bool = False,
    callback: Optional[Callable[[int, torch.Tensor, torch.Tensor], None]] = None,
) -> dict:
    """Generate a LookingGlass illusion with fake clean-space time travel.

    This variant keeps the normal LookingGlass clean-latent synchronization,
    but changes the repeated time-travel window. For a selected base step at
    `sigma`, it predicts all repeated clean latents at the same `sigma` without
    jumping to `next_sigma` or adding noise back between repeats. With
    `sync_repeats=2`, the sequence is:

        latent_sigma -> clean_1 -> clean_2 -> clean_3 -> latent_next_sigma

    The final noise-back move uses the velocity from the last fake denoise,
    i.e. from `clean_2` to `clean_3` in the example above. Outside the selected
    repeat window, the step runs once like a normal clean prediction followed
    by the move to `next_sigma`.
    """

    if not views:
        raise ValueError("at least one ViewSpec is required")

    device = pipe._execution_device if hasattr(pipe, "_execution_device") else torch.device("cuda")
    dtype = module_dtype(pipe.transformer)
    if generator is None and seed is not None:
        generator = torch.Generator(device=device).manual_seed(seed)

    prompts = [view.prompt for view in views]
    uvs = [resize_uv(view.uv.to(device), height, width) for view in views]
    do_cfg = guidance_scale is not None and guidance_scale > 1.0

    prompt_embeds, pooled_prompt_embeds = encode_sd3_prompts(
        pipe,
        prompts,
        negative_prompts=negative_prompts,
        device=device,
        do_classifier_free_guidance=do_cfg,
        max_sequence_length=max_sequence_length,
    )

    num_channels_latents = pipe.transformer.config.in_channels
    if correlated_initial_noise:
        base_latents = pipe.prepare_latents(
            1,
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents=None,
        )
        latent_height = base_latents.shape[-2]
        latent_width = base_latents.shape[-1]
        latent_view_uvs = [resize_uv(uv.to(device), latent_height, latent_width) for uv in uvs]
        latents = torch.cat(
            [
                sample_tensor_with_uv(
                    base_latents,
                    latent_view_uvs[idx],
                    sample_mode=lpw_sample_mode,
                    fill_value=0.0,
                )
                for idx in range(len(views))
            ],
            dim=0,
        )
    else:
        latents = pipe.prepare_latents(
            len(views),
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents=None,
        )

    timesteps = set_sd3_timesteps(pipe, latents, num_inference_steps, device=device)
    sigmas = pipe.scheduler.sigmas.to(device=device, dtype=latents.dtype)
    total_steps = len(timesteps)
    first_repeat = int(total_steps * sync_repeat_start)
    last_repeat = int(total_steps * sync_repeat_stop)
    repeat_count = max(0, int(sync_repeats))
    first_prioritize = int(total_steps * (1.0 - prioritize_fraction))

    transition_index = 0
    for step_index in range(total_steps):
        sigma = sigmas[step_index].to(device=latents.device, dtype=latents.dtype)
        next_sigma = sigmas[step_index + 1].to(device=latents.device, dtype=latents.dtype)
        timestep = timestep_from_sigma(pipe, sigma, device=latents.device)

        active_indices = None
        if prioritize_view is not None and prioritize_fraction > 0 and step_index >= first_prioritize:
            active_indices = [int(prioritize_view)]

        fake_repeats = repeat_count if first_repeat <= step_index < last_repeat and step_index < total_steps - 1 else 0
        current_latents = latents
        synced_velocity = None
        denoise_start = current_latents
        for _ in range(fake_repeats + 1):
            denoise_start = current_latents
            with torch.no_grad():
                velocity = predict_velocity_sd3(
                    pipe,
                    denoise_start,
                    timestep,
                    prompt_embeds,
                    pooled_prompt_embeds,
                    guidance_scale=guidance_scale,
                )

            clean_latents = denoise_start - sigma * velocity
            current_latents = synchronize_clean_latents(
                pipe,
                clean_latents,
                uvs,
                image_levels=image_levels,
                latent_levels=latent_levels,
                alpha=alpha,
                lpw_sample_mode=lpw_sample_mode,
                active_indices=active_indices,
            ).detach()
            synced_velocity = (denoise_start - current_latents) / sigma.clamp_min(1e-6)

        if synced_velocity is None:
            raise RuntimeError("fake time-travel loop did not run")
        latents_dtype = latents.dtype
        latents = flowmatch_euler_step(denoise_start, synced_velocity, sigma, next_sigma)
        latents = latents.to(latents_dtype).detach()

        if callback is not None:
            callback(transition_index, timestep, latents)
        transition_index += 1

    with torch.no_grad():
        decoded = vae_decode_tensor(pipe, latents)
        images = pipe.image_processor.postprocess(decoded, output_type="pil")

    return {
        "images": images,
        "latents": latents,
        "views": views,
        "prompts": prompts,
    }




@torch.no_grad()
def synchronize_tensors_with_lpw(
    tensors: torch.Tensor,
    uvs: Sequence[torch.Tensor],
    *,
    levels: int = 4,
    alpha: float = 0.35,
    sample_mode: str = "nearest",
    active_indices: Optional[Sequence[int]] = None,
) -> torch.Tensor:
    """Synchronize arbitrary view tensors through canonical LPW blending."""

    if tensors.shape[0] != len(uvs):
        raise ValueError("tensor batch and uvs must have the same length")

    device = tensors.device
    dtype = tensors.dtype
    active = list(range(tensors.shape[0])) if active_indices is None else list(active_indices)
    resized_uvs = [resize_uv(uv.to(device), tensors.shape[-2], tensors.shape[-1]) for uv in uvs]
    pyramids = [
        inverse_lpw(
            tensors[idx : idx + 1].float(),
            resized_uvs[idx],
            levels=levels,
            sample_mode=sample_mode,
        )
        for idx in active
    ]
    canonical_lp = blend_laplacian_pyramids(pyramids, alpha=alpha)
    canonical_gp = laplacian_to_gaussian(canonical_lp)

    synced = [
        forward_lpw_from_gaussian(
            canonical_gp,
            resized_uvs[idx],
            fill_value=0.0,
            sample_mode=sample_mode,
        )
        for idx in range(tensors.shape[0])
    ]
    return torch.cat(synced, dim=0).to(dtype=dtype)


@torch.no_grad()
def synchronize_clean_latents_lpw_ablation(
    pipe,
    clean_latents: torch.Tensor,
    uvs: Sequence[torch.Tensor],
    *,
    mode: str,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    lpw_sample_mode: str = "nearest",
    active_indices: Optional[Sequence[int]] = None,
) -> torch.Tensor:
    """Apply LPW-only variants for a custom Figure-5-style ablation."""

    clean_latents = clean_latents.detach()
    device = clean_latents.device

    if mode == "final_estimate_lpw":
        return synchronize_tensors_with_lpw(
            clean_latents,
            uvs,
            levels=latent_levels,
            alpha=alpha,
            sample_mode=lpw_sample_mode,
            active_indices=active_indices,
        )

    if mode == "vae_lpw":
        decoded = vae_decode_tensor(pipe, clean_latents)
        synced_images = synchronize_tensors_with_lpw(
            decoded,
            uvs,
            levels=image_levels,
            alpha=alpha,
            sample_mode=lpw_sample_mode,
            active_indices=active_indices,
        )
        return vae_encode_tensor(pipe, synced_images).to(device=device, dtype=clean_latents.dtype)

    if mode == "residual_lpw":
        return synchronize_clean_latents(
            pipe,
            clean_latents,
            uvs,
            image_levels=image_levels,
            latent_levels=latent_levels,
            alpha=alpha,
            lpw_sample_mode=lpw_sample_mode,
            active_indices=active_indices,
        )

    raise ValueError("mode must be one of: final_estimate_lpw, vae_lpw, residual_lpw")


@torch.no_grad()
def synchronize_clean_latents_for_figure5(
    pipe,
    clean_latents: torch.Tensor,
    view_uvs: Sequence[torch.Tensor],
    inverse_uvs: Sequence[torch.Tensor],
    *,
    mode: str,
    sample_mode: str = "nearest",
) -> torch.Tensor:
    """Apply the Section 4.1 ablation used in the paper's Figure 5."""

    clean_latents = clean_latents.detach()
    device = clean_latents.device
    with torch.no_grad():
        latent_uvs = [resize_uv(uv.to(device), clean_latents.shape[-2], clean_latents.shape[-1]) for uv in view_uvs]
        latent_inverse_uvs = [resize_uv(uv.to(device), clean_latents.shape[-2], clean_latents.shape[-1]) for uv in inverse_uvs]

        if mode == "final_estimate":
            return synchronize_tensors_with_uv(
                clean_latents,
                latent_uvs,
                latent_inverse_uvs,
                sample_mode=sample_mode,
            )

        decoded = vae_decode_tensor(pipe, clean_latents)
        image_uvs = [resize_uv(uv.to(device), decoded.shape[-2], decoded.shape[-1]) for uv in view_uvs]
        image_inverse_uvs = [resize_uv(uv.to(device), decoded.shape[-2], decoded.shape[-1]) for uv in inverse_uvs]
        synced_images = synchronize_tensors_with_uv(
            decoded,
            image_uvs,
            image_inverse_uvs,
            sample_mode=sample_mode,
        )
        synced_latents = vae_encode_tensor(pipe, synced_images).to(device=device, dtype=clean_latents.dtype)

        if mode == "vae":
            return synced_latents
        if mode != "residual":
            raise ValueError("mode must be one of: final_estimate, vae, residual")

        roundtrip = vae_encode_tensor(pipe, decoded).to(device=device, dtype=clean_latents.dtype)
        residuals = clean_latents - roundtrip
        synced_residuals = synchronize_tensors_with_uv(
            residuals,
            latent_uvs,
            latent_inverse_uvs,
            sample_mode=sample_mode,
        )
        return synced_latents + synced_residuals


@torch.no_grad()
def sample_figure5_ablation(
    pipe,
    views: Sequence[ViewSpec],
    inverse_uvs: Sequence[torch.Tensor],
    *,
    height: int = 1024,
    width: int = 1024,
    num_inference_steps: int = 30,
    guidance_scale: float = 4.5,
    seed: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    negative_prompts: Optional[Sequence[str]] = None,
    sample_mode: str = "nearest",
    max_sequence_length: int = 256,
    correlated_initial_noise: bool = True,
) -> dict[str, list]:
    """Generate Figure-5-style ablations.

    Variants:
    - `geng_latent`: synchronize the current noisy latents directly.
    - `final_estimate`: synchronize predicted clean latents in latent space.
    - `vae`: decode clean latents, synchronize in image space, then re-encode.
    - `residual`: add the VAE round-trip residual correction.

    If `correlated_initial_noise` is true, each view starts as a UV-transformed
    copy of one base latent. This is closer to Visual Anagrams/Geng-style
    correlated noise than drawing independent latent noise for each view.
    """

    if len(views) != len(inverse_uvs):
        raise ValueError("views and inverse_uvs must have the same length")

    device = pipe._execution_device if hasattr(pipe, "_execution_device") else torch.device("cuda")
    prompts = [view.prompt for view in views]
    view_uvs = [resize_uv(view.uv.to(device), height, width) for view in views]
    inverse_uvs = [resize_uv(uv.to(device), height, width) for uv in inverse_uvs]
    latent_height = height // pipe.vae_scale_factor
    latent_width = width // pipe.vae_scale_factor
    latent_view_uvs = [resize_uv(uv.to(device), latent_height, latent_width) for uv in view_uvs]
    latent_inverse_uvs = [resize_uv(uv.to(device), latent_height, latent_width) for uv in inverse_uvs]

    do_cfg = guidance_scale is not None and guidance_scale > 1.0
    prompt_embeds, pooled_prompt_embeds = encode_sd3_prompts(
        pipe,
        prompts,
        negative_prompts=negative_prompts,
        device=device,
        do_classifier_free_guidance=do_cfg,
        max_sequence_length=max_sequence_length,
    )

    variants = ["geng_latent", "final_estimate", "vae", "residual"]
    labels = ["Geng et al.", "+ Final Estimate", "+ VAE", "+ Residual Corr."]
    outputs: dict[str, list] = {}

    for variant, label in zip(variants, labels):
        if generator is None and seed is not None:
            local_generator = torch.Generator(device=device).manual_seed(seed)
        else:
            local_generator = generator

        num_channels_latents = pipe.transformer.config.in_channels
        if correlated_initial_noise:
            base_latents = pipe.prepare_latents(
                1,
                num_channels_latents,
                height,
                width,
                prompt_embeds.dtype,
                device,
                local_generator,
                latents=None,
            )
            latents = torch.cat(
                [
                    sample_tensor_with_uv(
                        base_latents,
                        latent_view_uvs[idx],
                        sample_mode=sample_mode,
                        fill_value=0.0,
                    )
                    for idx in range(len(views))
                ],
                dim=0,
            )
        else:
            latents = pipe.prepare_latents(
                len(views),
                num_channels_latents,
                height,
                width,
                prompt_embeds.dtype,
                device,
                local_generator,
                latents=None,
            )

        timesteps = set_sd3_timesteps(pipe, latents, num_inference_steps, device=device)
        for step_index, timestep in enumerate(timesteps):
            with torch.no_grad():
                if variant == "geng_latent":
                    latents = synchronize_tensors_with_uv(
                        latents.detach(),
                        latent_view_uvs,
                        latent_inverse_uvs,
                        sample_mode=sample_mode,
                    )

                velocity = predict_velocity_sd3(
                    pipe,
                    latents,
                    timestep,
                    prompt_embeds,
                    pooled_prompt_embeds,
                    guidance_scale=guidance_scale,
                )

                if variant == "geng_latent":
                    model_output = velocity
                else:
                    sigma = pipe.scheduler.sigmas[step_index].to(device=latents.device, dtype=latents.dtype)
                    clean_latents = latents - sigma * velocity
                    synced_clean = synchronize_clean_latents_for_figure5(
                        pipe,
                        clean_latents,
                        view_uvs,
                        inverse_uvs,
                        mode=variant,
                        sample_mode=sample_mode,
                    )
                    model_output = (latents - synced_clean) / sigma.clamp_min(1e-6)

                latents_dtype = latents.dtype
                latents = pipe.scheduler.step(model_output, timestep, latents.detach(), return_dict=False)[0]
                latents = latents.to(latents_dtype).detach()

        with torch.no_grad():
            decoded = vae_decode_tensor(pipe, latents)
            images = pipe.image_processor.postprocess(decoded, output_type="pil")
        outputs[label] = images
        del latents, decoded
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return outputs


@torch.no_grad()
def sample_figure5_lpw_ablation(
    pipe,
    views: Sequence[ViewSpec],
    *,
    height: int = 1024,
    width: int = 1024,
    num_inference_steps: int = 30,
    guidance_scale: float = 4.5,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    seed: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    negative_prompts: Optional[Sequence[str]] = None,
    lpw_sample_mode: str = "nearest",
    sync_repeat_start: float = 0.20,
    sync_repeat_stop: float = 0.80,
    sync_repeats: int = 1,
    prioritize_view: Optional[int] = 0,
    prioritize_fraction: float = 0.20,
    max_sequence_length: int = 256,
    correlated_initial_noise: bool = False,
    callback: Optional[Callable[[str, int, torch.Tensor, torch.Tensor], None]] = None,
) -> dict[str, list]:
    """Generate a custom Figure-5-style ablation where every variant uses LPW.

    Variants:
    - `final_estimate_lpw`: predicted clean latents synchronized with latent LPW.
    - `vae_lpw`: predicted clean latents decoded, synchronized with image LPW, then re-encoded.
    - `residual_lpw`: the full VAE LPW path plus latent residual correction.

    The time-travel and prioritization controls mirror `sample_lookingglass`,
    including forward/backward one-step sigma transitions for `sync_repeats`.
    """

    if not views:
        raise ValueError("at least one ViewSpec is required")

    device = pipe._execution_device if hasattr(pipe, "_execution_device") else torch.device("cuda")
    prompts = [view.prompt for view in views]
    view_uvs = [resize_uv(view.uv.to(device), height, width) for view in views]
    latent_height = height // pipe.vae_scale_factor
    latent_width = width // pipe.vae_scale_factor
    latent_view_uvs = [resize_uv(uv.to(device), latent_height, latent_width) for uv in view_uvs]

    do_cfg = guidance_scale is not None and guidance_scale > 1.0
    prompt_embeds, pooled_prompt_embeds = encode_sd3_prompts(
        pipe,
        prompts,
        negative_prompts=negative_prompts,
        device=device,
        do_classifier_free_guidance=do_cfg,
        max_sequence_length=max_sequence_length,
    )

    variants = ["final_estimate_lpw", "vae_lpw", "residual_lpw"]
    labels = ["Final Estimate + LPW", "+ VAE + LPW", "+ Residual Corr. + LPW"]
    outputs: dict[str, list] = {}

    for variant, label in zip(variants, labels):
        if generator is None and seed is not None:
            local_generator = torch.Generator(device=device).manual_seed(seed)
        else:
            local_generator = generator

        num_channels_latents = pipe.transformer.config.in_channels
        if correlated_initial_noise:
            base_latents = pipe.prepare_latents(
                1,
                num_channels_latents,
                height,
                width,
                prompt_embeds.dtype,
                device,
                local_generator,
                latents=None,
            )
            latents = torch.cat(
                [
                    sample_tensor_with_uv(
                        base_latents,
                        latent_view_uvs[idx],
                        sample_mode=lpw_sample_mode,
                        fill_value=0.0,
                    )
                    for idx in range(len(views))
                ],
                dim=0,
            )
        else:
            latents = pipe.prepare_latents(
                len(views),
                num_channels_latents,
                height,
                width,
                prompt_embeds.dtype,
                device,
                local_generator,
                latents=None,
            )

        timesteps = set_sd3_timesteps(pipe, latents, num_inference_steps, device=device)
        sigmas = pipe.scheduler.sigmas.to(device=device, dtype=latents.dtype)
        total_steps = len(timesteps)
        transitions = time_travel_transitions(
            total_steps,
            sync_repeat_start=sync_repeat_start,
            sync_repeat_stop=sync_repeat_stop,
            sync_repeats=sync_repeats,
        )
        first_prioritize = int(total_steps * (1.0 - prioritize_fraction))

        for transition_index, (step_index, sigma_index, next_sigma_index) in enumerate(transitions):
            with torch.no_grad():
                sigma = sigmas[sigma_index].to(device=latents.device, dtype=latents.dtype)
                next_sigma = sigmas[next_sigma_index].to(device=latents.device, dtype=latents.dtype)
                timestep = timestep_from_sigma(pipe, sigma, device=latents.device)
                velocity = predict_velocity_sd3(
                    pipe,
                    latents,
                    timestep,
                    prompt_embeds,
                    pooled_prompt_embeds,
                    guidance_scale=guidance_scale,
                )
                clean_latents = latents - sigma * velocity

                active_indices = None
                if prioritize_view is not None and prioritize_fraction > 0 and step_index >= first_prioritize:
                    active_indices = [int(prioritize_view)]

                synced_clean = synchronize_clean_latents_lpw_ablation(
                    pipe,
                    clean_latents,
                    view_uvs,
                    mode=variant,
                    image_levels=image_levels,
                    latent_levels=latent_levels,
                    alpha=alpha,
                    lpw_sample_mode=lpw_sample_mode,
                    active_indices=active_indices,
                )
                model_output = (latents - synced_clean) / sigma.clamp_min(1e-6)

                latents_dtype = latents.dtype
                latents = flowmatch_euler_step(latents.detach(), model_output, sigma, next_sigma)
                latents = latents.to(latents_dtype).detach()

                if callback is not None:
                    callback(label, transition_index, timestep, latents)

        with torch.no_grad():
            decoded = vae_decode_tensor(pipe, latents)
            images = pipe.image_processor.postprocess(decoded, output_type="pil")
        outputs[label] = images
        del latents, decoded
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return outputs


@dataclass
class FactorizedViewSpec:
    """A view with per-band text prompts for factorized diffusion.

    Each prompt controls a different frequency band of the view.  The image
    generated for band *i* is decomposed so that only its assigned frequency
    component survives; the components are then summed to form the final
    clean-latent estimate for that view.

    Attributes:
        name: Human-readable label for logging / filenames.
        prompts: One text prompt per frequency band.  Length 2 gives
            low/high; length 3 gives low/medium/high.
        uv: Target-to-canonical UV map, shape ``[H, W, 2]``.
        blur_sigma: Base Gaussian blur sigma for the frequency split.
            The low-pass kernel uses ``blur_sigma``; the medium-pass
            kernel (3-band) uses ``2 * blur_sigma``.
    """

    name: str
    prompts: list[str]
    uv: torch.Tensor
    blur_sigma: float = 5.0


def _decompose_blur(image: torch.Tensor, sigma: float) -> torch.Tensor:
    """Separable Gaussian blur used for frequency decomposition."""

    ks = int(2 * round(3 * sigma) + 1)
    if ks % 2 == 0:
        ks += 1
    x = torch.arange(ks, device=image.device, dtype=image.dtype) - ks // 2
    k1d = torch.exp(-x.pow(2) / (2 * sigma ** 2))
    k1d = k1d / k1d.sum()
    channels = image.shape[1]
    ky = k1d.view(1, 1, ks, 1).repeat(channels, 1, 1, 1)
    kx = k1d.view(1, 1, 1, ks).repeat(channels, 1, 1, 1)
    pad = ks // 2
    out = F.pad(image, (0, 0, pad, pad), mode="reflect")
    out = F.conv2d(out, ky, groups=channels)
    out = F.pad(out, (pad, pad, 0, 0), mode="reflect")
    out = F.conv2d(out, kx, groups=channels)
    return out


def _frequency_composite(
    band_images: list[torch.Tensor],
    blur_sigma: float,
) -> torch.Tensor:
    """Sum frequency-band images according to the factorized-diffusion recipe.

    For 2 bands:  composite = blur(x_low) + (x_high − blur(x_high)).
    For 3 bands:  composite = blur2(x_low)
                            + (blur1(x_med) − blur2(x_med))
                            + (x_high − blur1(x_high)).
    """

    n = len(band_images)
    if n == 2:
        low = _decompose_blur(band_images[0], blur_sigma)
        high = band_images[1] - _decompose_blur(band_images[1], blur_sigma)
        return low + high
    if n == 3:
        s1 = blur_sigma
        s2 = blur_sigma * 2
        low = _decompose_blur(band_images[0], s2)
        med = _decompose_blur(band_images[1], s1) - _decompose_blur(band_images[1], s2)
        high = band_images[2] - _decompose_blur(band_images[2], s1)
        return low + med + high
    raise ValueError(f"Expected 2 or 3 bands, got {n}")


@torch.no_grad()
def factorized_composite_clean_latents(
    pipe,
    per_view_band_latents: list[list[torch.Tensor]],
    blur_sigmas: Sequence[float],
) -> torch.Tensor:
    """Decode per-band clean latents, composite in image space, re-encode.

    Args:
        pipe: SD3 / SD3.5 pipeline (VAE used for decode / encode).
        per_view_band_latents: ``per_view_band_latents[view][band]`` is a
            single-view clean-latent tensor ``[1, C, H, W]``.
        blur_sigmas: One Gaussian sigma per view for the frequency split.
            Views with a single band skip compositing entirely.

    Returns:
        Tensor of shape ``[N_views, C, H, W]`` with composited clean latents.
    """

    composited: list[torch.Tensor] = []
    for band_latents, sigma in zip(per_view_band_latents, blur_sigmas):
        if len(band_latents) == 1:
            composited.append(band_latents[0])
            continue
        band_images = [vae_decode_tensor(pipe, z) for z in band_latents]
        comp_img = _frequency_composite(band_images, sigma)
        comp_latent = vae_encode_tensor(pipe, comp_img)
        composited.append(comp_latent)
    return torch.cat(composited, dim=0)


@torch.no_grad()
def sample_factorized_lookingglass(
    pipe,
    views: Sequence[FactorizedViewSpec],
    *,
    height: int = 1024,
    width: int = 1024,
    num_inference_steps: int = 30,
    guidance_scale: float = 4.5,
    image_levels: int = 6,
    latent_levels: int = 4,
    alpha: float = 0.35,
    lpw_sample_mode: str = "nearest",
    seed: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    negative_prompts: Optional[Sequence[str]] = None,
    sync_repeat_start: float = 0.20,
    sync_repeat_stop: float = 0.80,
    sync_repeats: int = 1,
    prioritize_view: Optional[int] = 0,
    prioritize_fraction: float = 0.20,
    max_sequence_length: int = 256,
    callback: Optional[Callable[[int, torch.Tensor, torch.Tensor], None]] = None,
) -> dict:
    """Generate a Factorized-LookingGlass illusion.

    Each view carries *B* prompts (one per frequency band).  At every
    denoising step the model is run once per prompt per view, producing
    *B* clean-latent estimates.  These are decoded to image space,
    frequency-decomposed, composited (low freq from prompt 0, high freq
    from prompt 1, …), re-encoded, and then fed into the standard
    LookingGlass LPW synchronization.

    Cost per step: ``N_views × B`` transformer forward passes (doubled
    with CFG).  For 2 views × 2 bands with CFG that is 8 passes per step.

    Returns the same dict shape as ``sample_lookingglass``.
    """

    if not views:
        raise ValueError("at least one FactorizedViewSpec is required")

    device = pipe._execution_device if hasattr(pipe, "_execution_device") else torch.device("cuda")
    dtype = module_dtype(pipe.transformer)
    if generator is None and seed is not None:
        generator = torch.Generator(device=device).manual_seed(seed)

    num_views = len(views)
    view_band_counts = [len(v.prompts) for v in views]
    total_bands = sum(view_band_counts)

    uvs = [resize_uv(view.uv.to(device), height, width) for view in views]
    do_cfg = guidance_scale is not None and guidance_scale > 1.0

    all_prompts: list[str] = []
    for view in views:
        all_prompts.extend(view.prompts)

    prompt_embeds, pooled_prompt_embeds = encode_sd3_prompts(
        pipe,
        all_prompts,
        negative_prompts=negative_prompts,
        device=device,
        do_classifier_free_guidance=do_cfg,
        max_sequence_length=max_sequence_length,
    )

    num_channels_latents = pipe.transformer.config.in_channels
    latents = pipe.prepare_latents(
        num_views,
        num_channels_latents,
        height,
        width,
        prompt_embeds.dtype,
        device,
        generator,
        latents=None,
    )

    timesteps = set_sd3_timesteps(pipe, latents, num_inference_steps, device=device)
    sigmas = pipe.scheduler.sigmas.to(device=device, dtype=latents.dtype)
    total_steps = len(timesteps)
    transitions = time_travel_transitions(
        total_steps,
        sync_repeat_start=sync_repeat_start,
        sync_repeat_stop=sync_repeat_stop,
        sync_repeats=sync_repeats,
    )
    first_prioritize = int(total_steps * (1.0 - prioritize_fraction))

    for transition_index, (step_index, sigma_index, next_sigma_index) in enumerate(transitions):
        sigma = sigmas[sigma_index].to(device=latents.device, dtype=latents.dtype)
        next_sigma = sigmas[next_sigma_index].to(device=latents.device, dtype=latents.dtype)
        timestep = timestep_from_sigma(pipe, sigma, device=latents.device)

        per_view_band_latents: list[list[torch.Tensor]] = []
        for view_idx in range(num_views):
            band_clean: list[torch.Tensor] = []
            base = sum(view_band_counts[:view_idx])
            for band_idx in range(view_band_counts[view_idx]):
                global_idx = base + band_idx
                if do_cfg:
                    pe = torch.cat([
                        prompt_embeds[global_idx : global_idx + 1],
                        prompt_embeds[total_bands + global_idx : total_bands + global_idx + 1],
                    ], dim=0)
                    ppe = torch.cat([
                        pooled_prompt_embeds[global_idx : global_idx + 1],
                        pooled_prompt_embeds[total_bands + global_idx : total_bands + global_idx + 1],
                    ], dim=0)
                else:
                    pe = prompt_embeds[global_idx : global_idx + 1]
                    ppe = pooled_prompt_embeds[global_idx : global_idx + 1]
                v = predict_velocity_sd3(
                    pipe,
                    latents[view_idx : view_idx + 1],
                    timestep,
                    pe,
                    ppe,
                    guidance_scale=guidance_scale,
                )
                band_clean.append(latents[view_idx : view_idx + 1] - sigma * v)
            per_view_band_latents.append(band_clean)

        blur_sigmas = [v.blur_sigma for v in views]
        composited_clean = factorized_composite_clean_latents(
            pipe,
            per_view_band_latents,
            blur_sigmas=blur_sigmas,
        )

        active_indices = None
        if prioritize_view is not None and prioritize_fraction > 0 and step_index >= first_prioritize:
            active_indices = [int(prioritize_view)]

        synced_clean = synchronize_clean_latents(
            pipe,
            composited_clean,
            uvs,
            image_levels=image_levels,
            latent_levels=latent_levels,
            alpha=alpha,
            lpw_sample_mode=lpw_sample_mode,
            active_indices=active_indices,
        )

        synced_velocity = (latents - synced_clean) / sigma.clamp_min(1e-6)
        latents_dtype = latents.dtype
        latents = flowmatch_euler_step(latents, synced_velocity, sigma, next_sigma)
        latents = latents.to(latents_dtype).detach()

        if callback is not None:
            callback(transition_index, timestep, latents)

    with torch.no_grad():
        decoded = vae_decode_tensor(pipe, latents)
        images = pipe.image_processor.postprocess(decoded, output_type="pil")

    return {
        "images": images,
        "latents": latents,
        "views": views,
        "prompts": all_prompts,
    }


def load_sd3_pipeline(
    model_id: str = "stabilityai/stable-diffusion-3.5-medium",
    *,
    torch_dtype: torch.dtype = torch.bfloat16,
    device: str = "cuda",
    cpu_offload: bool = False,
    token: str | None = None,
):
    """Load an SD3/SD3.5 pipeline for LookingGlass sampling."""

    import warnings

    warnings.filterwarnings("ignore", message="Flax classes are deprecated.*")
    from diffusers import StableDiffusion3Pipeline

    pretrained_kwargs = {"torch_dtype": torch_dtype}
    if token is not None:
        pretrained_kwargs["token"] = token
    pipe = StableDiffusion3Pipeline.from_pretrained(model_id, **pretrained_kwargs)
    if cpu_offload:
        pipe.enable_model_cpu_offload()
    else:
        pipe = pipe.to(device)
    pipe.set_progress_bar_config(disable=False)
    return pipe
